### ISSUE TITLE
Add running command line interface each directory

### ISSUE THREAD

**Issue by sysilion** [traveling-lumine/genshin_mod_manager#33]
Add run command line interface button beside on directory open button. 😋

**Comment by traveling-lumine** [comment]
Whose directory open folder? A category or a mod?
Anyways, the program should open cmd with its curdir set to the target folder. Am I correct?

**Comment by sysilion** [comment]
> Whose directory open button? A category or a mod? Anyways, the program should open cmd with its curdir set to the target folder. Am I correct?

Yeap. I guess both is okay. or only in category.

most of scripts is work subdirectory.
