### ISSUE TITLE
Add options in run one button

### ISSUE THREAD

**Issue by sysilion** [traveling-lumine/genshin_mod_manager#85]
# Add delay to 3d migoto

## Description
Delay setting for run 3d migoto after launcher

## Use Case
Launcher set directly running game

## Proposed Solution
Add delay setting form (integer, ms) in one button sub menu

------------

# Add Mod Manager close option

## Description
After running launcher and 3dmigoto, auto close Mod Manager

## Use Case
Run game and after close

## Proposed Solution
Add run and close button right of `Run 3d migoto & launcher`  

## Additional Context
simplify to button make icon and show tooltip when mouse over.

e.g. combine two icons check below
https://www.flaticon.com/free-icon/right-arrow_9210374
https://www.flaticon.com/free-icon/power_7103298

**Comment by traveling-lumine** [comment]
Hello! It seems that two issues have been combined into one here:
1. Adding a delay between running two programs when the one-click button is pressed.
2. Adding an option to close the manager after pressing the one-click button by adding a secondary command button.

Great suggestions, but generally it's a good practice to have a single use case per issue.

**Comment by traveling-lumine** [comment]
Working only on the 2nd one. I wasn't able to find a good reason to add delay between two program executions.
